

CREATE TABLE IF NOT EXISTS user (
	id INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(320) NOT NULL,
	password VARCHAR(64) NOT NULL,
	isAdmin TINYINT(1) NOT NULL DEFAULT 0,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	PRIMARY KEY(id),
	UNIQUE (email)
);


CREATE TABLE IF NOT EXISTS transaction (
	id INT NOT NULL AUTO_INCREMENT,
	t_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id INT NOT NULL,
	stock_symbol VARCHAR(20) NOT NULL,
	shares INT NOT NULL,
	t_price DECIMAL(10,2) NOT NULL,
	balance DECIMAL(10,2) NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS watchlist (
	id INT NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	stock_symbol VARCHAR(20) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);
